#include <QString>
#include <QMouseEvent>
#include <QApplication>
#include <QTranslator>
#include <QTextEdit>
#include <QScrollBar>
#include <QTime>
#include <QTimer>
#include <QRgb>
#include <QFileInfo>
#include <QDir>
#include <QCommandLineParser>
#include <QMessageBox>
#include <QProcess>
#include <QFileDialog>
#include <QMimeData>
#include <QTextCursor>
#include <QImageReader>
#include <QRegExp>
#include <QMenu>
#include <QColorDialog>
#include <QLabel>
#include <QDebug>
#include <QWidget>
#include <QTextDocument>
#include <QShortcut>
#include <QPainter>
#include <QPen>
#include <QtMath>
#include <QWheelEvent>
#include <QDataStream>
#include "noteedit.h"
#include "flatbutton.h"
#include "widget.h"
